#!/bin/bash

echo "🎨 Denis Macharov Font Application Script"
echo "========================================="
echo ""
echo "This script will help you apply the Denis Macharov font to all Text components."
echo ""

# List all component files that need font updates
echo "📱 Components that need font updates:"
echo "1. HomePage.tsx"
echo "2. Calendar.tsx" 
echo "3. UserProfile.tsx"
echo "4. AskMora.tsx"
echo "5. BreastScan.tsx"
echo "6. ScanResults.tsx"
echo "7. ScanReport.tsx"
echo "8. Questionnaire.tsx"
echo "9. Onboarding.tsx"
echo "10. ViewHistory.tsx"
echo "11. Login.tsx"
echo "12. BottomBar.tsx"
echo "13. Navbar.tsx"
echo ""

echo "🔧 How to apply fonts:"
echo ""

echo "Step 1: Add className to every Text component"
echo "---------------------------------------------"
echo "Search for: <Text"
echo "Replace with: <Text className=\"font-denis\""
echo ""

echo "Step 2: Use SmartText component for mixed content (text + icons)"
echo "----------------------------------------------------------------"
echo "import SmartText from './components/SmartText';"
echo "<SmartText>Hello World 🎉</SmartText>  # Auto-detects icons"
echo ""

echo "Step 3: Use consistent styling patterns"
echo "--------------------------------------"
echo "Headers: className=\"font-denis text-2xl font-bold text-center text-[#333]\""
echo "Body: className=\"font-denis text-base text-[#666] leading-6\""
echo "Buttons: className=\"font-denis text-lg font-semibold text-white\""
echo "Labels: className=\"font-denis text-sm font-medium text-[#8B5CF6]\""
echo ""

echo "Step 4: Example transformations"
echo "------------------------------"
echo ""
echo "BEFORE:"
echo "<Text>Hello World</Text>"
echo ""
echo "AFTER:"
echo "<Text className=\"font-denis text-base text-[#333]\">Hello World</Text>"
echo ""

echo "Step 5: Quick find and replace"
echo "------------------------------"
echo "Use your code editor's find and replace:"
echo "Find: <Text"
echo "Replace: <Text className=\"font-denis\""
echo ""
echo "Then manually adjust className to include other styling as needed."
echo ""

echo "📝 Note: You must manually add the font class to each Text component."
echo "React Native doesn't support automatic font inheritance like web browsers."
echo ""

echo "🎯 Icon Preservation:"
echo "- Use SmartText component for content with emojis/icons"
echo "- Denis Macharov font is applied only to text, not icons"
echo "- Icons will remain visible and properly rendered"
echo ""

echo "✅ After applying fonts:"
echo "1. Restart your app"
echo "2. Check each screen"
echo "3. Verify font is applied"
echo "4. Test on different devices"
echo "5. Verify icons are still visible"
echo ""

echo "🎯 The Denis Macharov font is ready - just needs to be applied to each Text component!"
echo "This font should provide better text rendering while preserving your icons."
